"""Build the dependency-free static portfolio. Run: python3 tools/build.py."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
PROJECTS = [
    dict(slug='stereo', number='01', name='Stereo perception', theme='',
         title='Turning sparse observations into usable obstacle geometry.',
         summary='A useful representation of thin obstacles, even when depth observations are sparse.',
         topic='GEOMETRY + SEMANTICS',
         lead='Thin obstacles can be visible in an image and still be poorly represented in depth. My work focused on making that evidence useful to a robot, alongside ground and floor-surface post-processing.',
         role='Thin-obstacle representation, ground estimation, floor-surface fusion and runtime optimization.',
         context='Stereo-led consumer-robot perception, supported by IMU and odometry information.',
         sections=[
             ('The problem', 'Seeing an object is not enough.', '''<p>A thin cable may occupy only a small part of the image. Its valid depth observations can be too sparse to form a useful obstacle representation. Simply carrying a semantic label on the available points leaves the geometric gap unresolved.</p><p>The engineering question was how to turn complementary evidence into geometry that downstream perception could use, while keeping uncertainty visible.</p>'''),
             ('My contribution', 'Build the representation around the evidence.', '''<p>I contributed a fusion-informed way of constructing a thin-obstacle representation, combining geometric observations with semantic evidence. This addressed the sparsity of the available points rather than relying only on labeling them.</p><div class="result"><div class="eyebrow">Representative outcome</div><p>Addressed the sparse-point limitation in thin-obstacle perception by changing how useful obstacle geometry is formed.</p></div><p>That is the central contribution shown here. The interactive scene illustrates the difference between sparse observations and an inferred geometric representation; it is an independent explanation of the problem.</p>'''),
             ('Engineering judgment', 'Different scene elements need different treatment.', '''<div class="decision-grid"><div class="decision"><h3>Ground as a geometric reference</h3><p>I introduced ground estimation from disparity. Establishing the supporting surface provides context for interpreting other scene geometry.</p></div><div class="decision"><h3>Floor surfaces from complementary cues</h3><p>I developed floor-surface post-processing that combines geometric and semantic information when model output alone has limited confidence.</p></div><div class="decision"><h3>Reuse with adaptation</h3><p>I adapted an existing geometric classification pipeline from another sensor platform to stereo inputs, then optimized its runtime.</p></div><div class="decision"><h3>Sensor context matters</h3><p>Stereo was the leading observation source. Supporting IMU and odometry information formed part of the broader perception context.</p></div></div>'''),
             ('Scope & limits', 'A public explanation of the contribution.', '''<p>The claims above describe my engineering responsibilities and the problem addressed. No latency, detection-rate or benchmark claims are made here because there is no public measurement set to support them.</p><p>The demonstration does not reproduce a product's thresholds, data flow or full algorithm. Its geometry is illustrative, and the added representation should be read as a hypothesis rather than an additional depth measurement.</p>''')]),
    dict(slug='lidar', number='02', name='LiDAR perception', theme='blue',
         title='Keeping moving targets consistent across observations.',
         summary='Tracking dynamic targets in an established outdoor perception system.',
         topic='TEMPORAL CONSISTENCY',
         lead='An outdoor scene changes between observations. I led the introduction of tracking into an existing perception framework, while implementing and maintaining the system through deployment issues.',
         role='Tracking integration, implementation, maintenance and deployment fixes.',
         context='LiDAR-led outdoor-robot perception, with supporting IMU and odometry information.',
         sections=[
             ('The problem', 'A static map meets a moving scene.', '''<p>People and pets move through outdoor environments. A static scene representation alone can struggle to describe how those observations evolve. Treating each observation in isolation also loses the continuity that makes a moving target easier to interpret.</p><p>Outdoor geometry posed another challenge: a representation influenced by indoor, two-dimensional grids needed to preserve relevant height information, including overhanging obstacles.</p>'''),
             ('My contribution', 'Add continuity to an existing framework.', '''<p>The main system architecture had already been selected before I joined. My responsibility was to implement and maintain the perception system, resolve deployment problems, and extend it where the established representation was insufficient.</p><p>I led the introduction of an object-tracking module to address dynamic targets. This added a temporal representation to a system that also had to reason about static scene structure.</p><div class="result"><div class="eyebrow">Representative outcome</div><p>Introduced tracking into the established system to handle the limits of static representations around moving targets.</p></div>'''),
             ('Engineering judgment', 'Time and height both carry information.', '''<div class="decision-grid"><div class="decision"><h3>Observations versus target state</h3><p>A return describes what is observed now. A track represents continuity across observations. The illustration separates those two ideas so they can be inspected independently.</p></div><div class="decision"><h3>Height beyond a flat grid</h3><p>I worked on deployment issues involving height structure and overhanging obstacles, where a purely two-dimensional interpretation was insufficient.</p></div><div class="decision"><h3>Motion in context</h3><p>Supporting robot-motion information helps distinguish changes in observations from changes caused by the observing platform.</p></div><div class="decision"><h3>Extend an operating system</h3><p>The work was integration within an established framework: respecting existing interfaces and maintaining deployed behavior while adding capability.</p></div></div>'''),
             ('Scope & limits', 'Ownership, stated precisely.', '''<p>I led the tracking addition, rather than designing the original perception architecture. The account here focuses on implementation, integration and the deployment problems I helped resolve.</p><p>The synthetic track demonstrates temporal continuity and a short occlusion. Its dotted segment is an illustrative continuation, not a claim about a product's prediction policy or performance. No internal recordings, parameters or deployment metrics are shown.</p>''')]),
    dict(slug='collision', number='03', name='Physics simulation', theme='gold',
         title='Adding algorithm choices to a collision engine.',
         summary='SAP, a BVH midphase and GJK integrated alongside existing collision algorithms.',
         topic='SPATIAL REASONING',
         lead='The challenge was to extend an existing physics-simulation engine with more collision-detection capabilities, while adapting to its types, interfaces and data flow.',
         role='Integration of broadphase, midphase and narrowphase algorithm options.',
         context='An existing, closed-source physics-simulation engine.',
         sections=[
             ('The problem', 'Geometry queries need a path through the engine.', '''<p>The engine had a limited set of collision-detection options. Adding an algorithm required more than reproducing its mathematics: it had to work with the engine's own object representations and the way geometry moved between query stages.</p><p>Broadphase, midphase and narrowphase solve different parts of that task. A useful extension had to fit those responsibilities without discarding existing behavior.</p>'''),
             ('My contribution', 'Extend three stages, preserve existing options.', '''<div class="decision-grid"><div class="decision"><h3>Broadphase · Sweep and Prune</h3><p>I introduced SAP as an additional way to identify potential collision candidates from spatial bounds.</p></div><div class="decision"><h3>Midphase · Bounding volume hierarchy</h3><p>I introduced a BVH midphase to organize geometry for subsequent collision queries.</p></div><div class="decision"><h3>Narrowphase · GJK</h3><p>I integrated GJK alongside existing algorithms, including SAT, to expand convex-geometry query options.</p></div><div class="decision"><h3>Integration · Engine adaptation</h3><p>I adapted the algorithms to the host engine's basic types, interfaces and data flow.</p></div></div><div class="result"><div class="eyebrow">Representative outcome</div><p>Expanded the engine's algorithm options across collision-query stages while retaining the original choices.</p></div>'''),
             ('Engineering judgment', 'An established algorithm is still integration work.', '''<p>These were integrations of established algorithms, rather than new algorithm inventions. The engineering contribution was making them usable within another engine's constraints.</p><p>The added capabilities complemented the original implementation. Keeping the existing options available avoided presenting the work as a wholesale replacement of the collision system.</p><p>The illustration shows candidate filtering, hierarchical bounds and convex queries as distinct concepts. It does not encode the internal engine's object model or implementation.</p>'''),
             ('Scope & limits', 'Capability, without invented benchmark claims.', '''<p>The publicly described result is broader functionality. There is no published benchmark here establishing a particular speedup or accuracy improvement.</p><p>The host engine remains unnamed. This page explains the integration contribution without publishing its source, internal class definitions or architecture.</p>''')]),
    dict(slug='motion', number='04', name='Vision-based motion analysis', theme='purple',
         title='A common spatial reference despite camera movement.',
         summary='Aligning climbing-video frames to a wall template for movement analysis.',
         topic='GEOMETRIC ALIGNMENT',
         lead='My master’s research connected video observations to a common wall reference, so camera movement would not define the apparent trajectory of the climber.',
         role='Frame-to-template alignment and integration of visual observations for movement analysis.',
         context='Master’s research · Robotic Systems Engineering · RWTH Aachen University.',
         sections=[
             ('The problem', 'The camera moves; the reference should not.', '''<p>Image coordinates change when a camera moves, even if the observed scene has not changed. Reading a climbing trajectory directly from those coordinates can mix camera movement with the climber's movement.</p><p>The central task was to align local video frames to a common wall template and establish a spatial reference for subsequent analysis.</p>'''),
             ('My contribution', 'Connect each frame to the wall template.', '''<p>I used geometric features to align local video frames to a wall template and map observations into that reference. This supported trajectory and velocity analysis despite camera movement.</p><p>The broader research pipeline combined hold detection using YOLO and human-pose estimation using MediaPipe, with movement and joint-angle analysis.</p><div class="result"><div class="eyebrow">Representative outcome</div><p>Established a common wall reference for interpreting observations across moving-camera video frames.</p></div>'''),
             ('Engineering judgment', 'Alignment is a prerequisite for interpretation.', '''<p>The middle panel explicitly distinguishes the observed frame from the reference template. Corresponding points communicate the alignment task before the trajectory is interpreted.</p><p>Hold detection and pose estimation provide observations; geometric alignment makes observations from different frames comparable. The movement trace illustrates that distinction.</p><p>This page uses an independently generated animation because the original research videos are unavailable. The displayed trace is explanatory, not a recovered experiment.</p>'''),
             ('Scope & limits', 'A monocular reference has limits.', '''<p>Monocular depth ambiguity remains a limitation. A wall-aligned image reference is not a complete three-dimensional reconstruction of the climber's movement.</p><p>The synthetic animation does not establish measurement accuracy or research performance. No unavailable recordings or reconstructed experimental metrics are presented as evidence.</p>''')]),
]

def head(title, description, prefix):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>{escape(title)}</title><meta name="description" content="{escape(description, quote=True)}"><link rel="icon" type="image/svg+xml" href="{prefix}assets/favicon.svg"><link rel="stylesheet" href="{prefix}assets/style.css"><script src="{prefix}assets/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>'''

def header(prefix):
    home = prefix + 'index.html'
    return f'''<header><div class="wrap"><a class="brand" href="{home}" aria-label="Merci homepage">Merci<span>.</span></a><nav aria-label="Main navigation"><a href="{home}#work">Work</a><a href="{home}#about">About</a><a href="{home}#contact">Contact</a></nav></div></header>'''

def footer(prefix):
    return f'''<footer><div class="wrap"><span>Merci · Geometry, perception & simulation</span><div class="footer-links"><a href="https://github.com/hyandnn">GitHub</a><a href="mailto:haoling.yang@rwth-aachen.de">Email</a></div></div></footer></body></html>'''

def card(p):
    if p['slug'] in ('stereo','lidar'):
        visual = f'<canvas data-scene="{p["slug"]}" data-preview="true" role="img" aria-label="Synthetic top-view {p["name"]} illustration"></canvas>'
    else:
        visual = f'<img src="assets/{p["slug"]}-preview.png" width="1080" height="380" loading="lazy" alt="Synthetic {p["name"]} conceptual illustration">'
    return f'''<a class="project-card {p['theme']}" href="projects/{p['slug']}.html"><div class="card-view">{visual}</div><div class="card-copy"><div class="card-heading"><span class="index">{p['number']}</span><h3>{p['name']}</h3></div><p>{p['summary']}</p><div class="card-foot"><span class="mono">{p['topic']}</span><span>Read case study</span></div></div></a>'''

home = head('Merci — Perception Algorithm Engineer', 'Perception engineering in consumer robotics. Selected work in stereo, LiDAR, collision detection and visual motion analysis.', '') + header('') + '''<main id="main">
<section class="hero" aria-labelledby="hero-title"><div><div class="eyebrow">Perception Algorithm Engineer</div><h1 id="hero-title">From observations<br>to <span>geometry.</span></h1><p class="intro">I’m Merci. I build perception software that turns imperfect sensor observations into useful geometry for robots.</p><div class="hero-actions"><a class="text-link" href="#work">Explore selected work</a><a class="text-link" href="https://github.com/hyandnn">GitHub profile</a></div></div><div class="hero-visual"><div class="visual-top mono"><span>GEOMETRY / TEMPORAL CONTEXT</span><span>SYNTHETIC</span></div><canvas data-scene="hero" role="img" aria-label="Isometric conceptual visualization of observed points and scene geometry"></canvas><div class="visual-bottom"><span>Observations → representation</span><span>Conceptual illustration</span></div></div></section>
<div class="principles"><div><b>Perception in consumer robotics</b><p>Stereo-led and LiDAR-led systems</p></div><div><b>Geometry with sensor context</b><p>Supporting IMU and odometry information</p></div><div><b>Engineering beyond the model</b><p>Integration, deployment and runtime efficiency</p></div></div>
<section id="work" aria-labelledby="work-title"><div class="section-top"><div><div class="eyebrow">Selected work / 01—04</div><h2 id="work-title">Four problems.<br>Concrete contributions.</h2></div><p>What I worked on, what changed, and the engineering decisions behind it.</p></div><div class="work-grid">''' + ''.join(card(p) for p in PROJECTS) + '''</div><p class="notice">Visuals are independently created conceptual illustrations using synthetic data. They do not show product recordings, internal implementations or measured research results.</p></section>
<section class="about" id="about" aria-labelledby="about-title"><div><div class="eyebrow">About / Merci</div><h2 id="about-title">Geometry.<br>Context.<br>Implementation.</h2></div><div class="about-text"><p>I work as a Perception Algorithm Engineer in consumer robotics. My focus spans geometric reasoning, model post-processing, temporal consistency and efficient C++ implementation.</p><p>I hold an M.Sc. in <b>Robotic Systems Engineering</b> from <b>RWTH Aachen University</b>. My earlier work includes physics-simulation integration and vision-based movement analysis.</p><div class="toolkit"><div><b>Implementation</b><p>C++ · Python · CMake<br>Profiling & runtime optimization</p></div><div><b>Perception</b><p>OpenCV · Point clouds<br>Geometry, semantics & tracking</p></div><div><b>Simulation</b><p>Collision detection<br>Spatial hierarchies & engine integration</p></div></div><p style="font-size:.9rem;margin-top:24px">Additional research: a small neural-network surrogate for manufacturing simulation, paired with an interactive interface.</p></div></section>
<section class="contact" id="contact" aria-labelledby="contact-title"><div><div class="eyebrow">Contact</div><h2 id="contact-title">Let’s talk engineering.</h2><p>Perception, geometry and systems that work in practice.</p></div><a class="text-link" href="mailto:haoling.yang@rwth-aachen.de">haoling.yang@rwth-aachen.de</a></section></main>''' + footer('')
(ROOT / 'index.html').write_text(home)

def demo(p):
    slug = p['slug']
    if slug in ('stereo','lidar'):
        labels = [('points','Observations'),('geometry','Geometry')] if slug == 'stereo' else [('points','Returns'),('rays','Sampled rays'),('tracks','Track')]
        controls = ''.join(f'<label><input type="checkbox" data-layer="{key}" checked>{label}</label>' for key,label in labels)
        caption = 'Top view. Depth-valid samples form surfaces with gaps and occlusion; the cyan thin-obstacle representation is illustrative inferred geometry.' if slug == 'stereo' else 'Top view. Angular samples stop at the first surface. A moving target passes behind a static obstacle; the dotted track segment illustrates continuity during occlusion.'
        return f'''<div class="demo" data-demo="{slug}"><div class="demo-head"><span>Explore the concept · {p['name']}</span><span>Independent synthetic demonstration</span></div><canvas data-scene="{slug}" role="img" aria-label="{escape(caption)}"></canvas><div class="demo-controls"><button type="button" data-play aria-pressed="false">Pause</button><label class="timeline"><span class="sr-label" hidden>Time</span><input type="range" min="0" max="1000" value="0" data-time aria-label="Demonstration time"><output data-time-label>0.0 s</output></label><div class="layers" aria-label="Visualization layers">{controls}</div></div><p class="demo-caption">{caption}</p></div>'''
    return f'''<div class="demo" data-media-demo><div class="demo-head"><span>Conceptual sequence · {p['name']}</span><span>Independent synthetic illustration</span></div><div class="media-scroll"><img class="wide-image" src="../assets/{slug}-preview.png" data-static="../assets/{slug}-preview.png" data-motion="../assets/{slug}.gif" width="1080" height="380" alt="{'Broadphase candidates, BVH hierarchy and convex geometry query.' if slug=='collision' else 'Pose observations, video-frame correspondence with a wall template, and an illustrative movement trace.'}"></div><div class="media-row"><button class="media-toggle" type="button" aria-pressed="false">Play illustration</button><small>Static by default. On small screens, scroll the illustration horizontally.</small></div></div>'''

for i,p in enumerate(PROJECTS):
    body = head(p['name']+' — Merci', p['summary'], '../') + header('../')
    body += f'''<main id="main" class="{p['theme']}"><a class="back" href="../index.html#work">All selected work</a><section class="case-head"><div class="eyebrow">{p['number']} / {p['name']}</div><h1>{p['title']}</h1><p class="lead">{p['lead']}</p><div class="case-meta"><div><span class="label mono">MY ROLE</span><p>{p['role']}</p></div><div><span class="label mono">CONTEXT</span><p>{p['context']}</p></div></div></section>'''
    body += demo(p)
    for k,(label,title,content) in enumerate(p['sections']):
        body += f'<section class="story"><div class="story-index mono">0{k+1} / {label}</div><div class="story-body"><h2>{title}</h2>{content}</div></section>'
    prev,nxt = PROJECTS[(i-1)%4], PROJECTS[(i+1)%4]
    body += f'''<div class="boundary">All demonstrations use synthetic data. Project descriptions are limited to publicly shareable responsibilities and conceptual explanations.</div><div class="case-nav"><div><small>Previous case</small><a href="{prev['slug']}.html">{prev['name']}</a></div><div><small>Next case</small><a href="{nxt['slug']}.html">{nxt['name']}</a></div></div></main>''' + footer('../')
    (ROOT/'projects'/f'{p["slug"]}.html').write_text(body)

(ROOT/'404.html').write_text(head('Page not found — Merci', 'Return to Merci’s portfolio.', '')+header('')+'<main id="main" class="empty-page"><div class="eyebrow">404</div><h1>Page not found.</h1><p class="muted" style="margin-top:24px">This address does not point to a case study.</p><a class="text-link" href="index.html">Return to the portfolio</a></main>'+footer(''))
print('Built homepage, 4 case studies and 404 page.')
